pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r * public/ || true
    - rm -rf public/.gitlab-ci.yml public/public
  artifacts:
    paths:
      - public
  only:
    - master
    - main
